<?php

namespace App\Http\Controllers\Api\V1;

use App\Enums\ExportModule;
use App\Enums\ExportStatus;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V1\StoreExportRequest;
use App\Http\Resources\Api\ExportResource;
use App\Jobs\GeneratePingResultExportJob;
use App\Jobs\GenerateSpeedResultExportJob;
use App\Models\ExportRequest;
use App\Models\User;
use Dedoc\Scramble\Attributes\Endpoint;
use Dedoc\Scramble\Attributes\Group;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Resources\Json\JsonResource;
use Symfony\Component\HttpFoundation\StreamedResponse;

#[Group(
    name: 'Exports',
    description: 'Queue asynchronous exports of speedtest and ping results. Exports are generated by queued jobs and become downloadable once completed.',
    weight: 3,
)]
/**
 * Export Endpoints
 *
 * Queue asynchronous exports of speedtest and ping results. Exports are
 * generated by queued jobs and become downloadable once completed.
 */
class ExportController extends Controller
{
    /**
     * List the authenticated user's export requests, newest first.
     *
     * @queryParam per_page int Default: 25. Max: 100. Minimum: 1.
     * @queryParam page int Default: 1. Current page number.
     * @queryParam status string Filter by status (pending, processing, completed, failed).
     *
     * @param Request $request
     */
    #[Endpoint(title: 'List exports', description: "List the authenticated user's export requests, newest first.")]
    public function index(Request $request): AnonymousResourceCollection
    {
        $perPage = min(max((int) $request->query('per_page', 25), 1), 100);

        /** @var User $user */
        $user = $request->user();

        $exports = ExportRequest::query()
            ->where('user_id', $user->id)
            ->when(
                $request->query('status'),
                static fn ($query, $status) => $query->where('status', $status)
            )
            ->latest()
            ->paginate($perPage)
            ->withQueryString();

        return ExportResource::collection($exports)->additional([
            'success' => filled($exports),
            'code'    => 200,
        ]);
    }

    /**
     * Queue a new export.
     *
     * Dispatches the appropriate generation job and returns 202 Accepted.
     * The export becomes available via the download endpoint once its
     * status changes to `completed`.
     *
     * @param StoreExportRequest $request
     */
    #[Endpoint(title: 'Queue export', description: 'Queue a new export of speedtest or ping results. Returns 202 Accepted; the export becomes downloadable once its status changes to completed.')]
    public function store(StoreExportRequest $request): JsonResponse
    {
        $validated = $request->validated();
        $module = ExportModule::from($validated['module']);

        /** @var User $user */
        $user = $request->user();

        $filters = $module === ExportModule::PingResult
            ? [
                'target'    => $validated['target'] ?? null,
                'date_from' => $validated['date_from'],
                'date_to'   => $validated['date_to'],
            ]
            : [
                'provider'  => $validated['provider'] ?? null,
                'date_from' => $validated['date_from'],
                'date_to'   => $validated['date_to'],
            ];

        $export = ExportRequest::query()->create([
            'user_id' => $user->id,
            'module'  => $module,
            'format'  => $validated['format'],
            'status'  => ExportStatus::Pending,
            'filters' => $filters,
        ]);

        match ($module) {
            ExportModule::PingResult => dispatch(new GeneratePingResultExportJob($export)),
            default                  => dispatch(new GenerateSpeedResultExportJob($export)),
        };

        return ExportResource::make($export)
            ->additional([
                'success' => true,
                'code'    => 202,
                'message' => 'Export queued successfully.',
            ])
            ->response()
            ->setStatusCode(202);
    }

    /**
     * Show a single export request owned by the authenticated user.
     *
     * @param Request       $request
     * @param ExportRequest $exportRequest
     */
    #[Endpoint(title: 'Show export', description: 'Show a single export request owned by the authenticated user.')]
    public function show(Request $request, ExportRequest $exportRequest): JsonResource
    {
        $this->ensureOwned($request, $exportRequest);

        return ExportResource::make($exportRequest)->additional([
            'success' => true,
            'code'    => 200,
        ]);
    }

    /**
     * Download a completed export file.
     *
     * Returns 404 when the export is not completed, its file is missing,
     * or the file has expired (410).
     *
     * @param Request       $request
     * @param ExportRequest $exportRequest
     */
    #[Endpoint(title: 'Download export', description: 'Download a completed export file. Returns 404 when the export is not completed or its file is missing, and 410 when the file has expired.')]
    public function download(Request $request, ExportRequest $exportRequest): StreamedResponse
    {
        $this->ensureOwned($request, $exportRequest);

        abort_if($exportRequest->status !== ExportStatus::Completed, 404, 'Export not ready.');
        abort_if($exportRequest->file_path === null, 404, 'Export file missing.');
        abort_if($exportRequest->expires_at?->isPast(), 410, 'Export has expired.');

        $fullPath = storage_path("app/private/{$exportRequest->file_path}");

        abort_unless(file_exists($fullPath), 404, 'Export file not found.');

        $filename = basename($fullPath);

        return response()->streamDownload(
            static function () use ($fullPath): void {
                readfile($fullPath);
            },
            $filename,
            ['Content-Type' => $exportRequest->format->mimeType()],
        );
    }

    /**
     * Ensure the export belongs to the authenticated user.
     *
     * @param Request       $request
     * @param ExportRequest $exportRequest
     */
    private function ensureOwned(Request $request, ExportRequest $exportRequest): void
    {
        abort_if(
            (int) $exportRequest->user_id !== (int) $request->user()?->id,
            404,
            'Export not found.',
        );
    }
}
