name: linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun install

      - name: Run Pint
        run: vendor/bin/pint

      - name: Format Frontend
        run: bun run format

      - name: Lint Frontend
        run: bun run lint

      # uncomment this if you want to commit the changes to the repository
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated linter fixes
          commit_options: '--no-verify'
