name: PHPStan

on:
  push:
    branches:
      - 2.x
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'
  pull_request:
    branches:
      - 2.x

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' && github.repository == 'MarJose123/Zepeed' }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github
